2024-11-05 22:24:12,645 | WARNING | Неверный тип данных для объекта Runner
Traceback (most recent call last):
  File "C:\Users\vmvlad\PycharmProjects\DB\tests_12_4.py", line 14, in test_run1
    runner2 = Runner(1, 10)
  File "C:\Users\vmvlad\PycharmProjects\DB\rt_with_exceptions.py", line 6, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано int
2024-11-05 22:24:12,646 | WARNING | Неверная скорость для Runner
Traceback (most recent call last):
  File "C:\Users\vmvlad\PycharmProjects\DB\tests_12_4.py", line 26, in test_walk1
    runner1 = Runner('runner1', -5)
  File "C:\Users\vmvlad\PycharmProjects\DB\rt_with_exceptions.py", line 11, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -5
